# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               BeingGeek
tagline:             'Blog like a geek'
description:         ''
url:                 http://blankspace007.github.io
baseurl:             /
paginate:            7

# About/contact
author:
  name:              hoping_sir
  url:               
  email:             1059710422@qq.com

# Custom vars
version:             1.0

# Social Media
github:				http://github.com/BlankSpace007 
twitter:			http://twitter.com/ariestiyansyah
disqus:             testnaringu

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu